/// Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_MEDIUM_1 = 10.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_CARD_MEDIUM_3 = 15.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;


const TEXT_REGULAR_1X = 14.0;
const TEXT_REGULAR = 12.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_REGULAR_3X = 18.0;
const TEXT_REGULAR_4X = 20.0;
const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_SMALL = 10.0;
const TEXT_BIG = 32.0;


/// App Specific
const BANNER_SECTION_HEIGHT = 200.0;
const BANNER_PLAY_BUTTON_SIZE = 56.0;
const MOVIE_LIST_HEIGHT = 270.0;
const SHOW_CASES_HEIGHT = 240.0;
const MOVIE_LIST_ITEM_WIDTH = 180.0;
const MOVIE_DETAILS_SCREEN_SLIVER_APP_BAR_HEIGHT = 200.0;
const BORDER_RADIUS = 8.0;
const LOGIN_PAGE_BUTTON_HEIGHT = 43.5;


const CHECK_OUT_HEIGHT = 700.0;

const CLIP_CIRCLE_SIZE = 40.0;

const TICKET_DETAILS_AMOUNT_TOTAL_SECTION_HEIGHT = 40.0;

const TICKET_DETAILS_PAGE_DELETE_ICON_SIZE = 25.0;

const CINEMA_DETAIL_PAGE_FACILITIES_ICON_SIZE = 40.0;

const SIZE_BOX_HEIGHT_SMALL = 10.0;

const SIZE_BOX_HEIGHT_MEDIUM = 15.0;

const SIZE_BOX_HEIGHT_MEDIUM_1 = 20.0;

const FACILITIES_ICON_SIZE = 15.80;

const MOVIE_VIEW_TYPE_HEIGHT = 30.0;

const VERIFITED_YOUR_PH_NO_AND_COUNTRY_CODE_SPACE = 80.0;

const VERIFY_YOUR_PHONE_NUMBER_TEXT_SIZE = 22.0;

const PIN_THEME_BORDER_RADIUS = 6.0;


