///Hive Types
const int HIVE_TYPE_ID_CITY_VO = 1;
const int HIVE_TYPE_ID_USER_DATA_VO = 2;
const int HIVE_TYPE_ID_MOVIE_VO = 3;
const int HIVE_TYPE_ID_CINEMA_TIMESLOT_STATUS_COLOR_VO = 4;

///Box Names
const String BOX_NAME_CITY_VO = "BOX_NAME_CITY_VO";
const String BOX_NAME_USER_DATA_VO = "BOX_NAME_USER_DATA_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_CINEMA_TIMESLOT_STATUS_COLOR_VO = "BOX_NAME_CINEMA_TIMESLOT_STATUS_COLOR_VO";